import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Invente 6.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the official SSN Invente 6.0 Website
        </h1>

        <div className={styles.grid}>
          
          <Link href="/signin">
            <a className={styles.card}>
              <h2>Signin</h2>
            </a>
          </Link>

          <Link href="/signup">
            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Signup</h2>
            </a>
          </Link>
        </div>
      </main>

    </div >
  )
}
